lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: knowledgepixels/pages-theme
plugins:
- jekyll-remote-theme
title: "Nanopub Space"
description: "Nanopub Space: project application for NGI Zero Core"
